package ru.vsu.cs.kiselev.cg;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;

public class ObjWriter {
    public static void write(String filename, Model model) throws IOException {
        StringBuilder sb = new StringBuilder();

        sb.append("# Generated by Triangulation Project\n");
        sb.append("o TriangulatedModel\n");

        for (Vector3f v : model.vertices) {
            sb.append(String.format("v %f %f %f\n", v.x, v.y, v.z));
        }
        sb.append("\n");

        for (ArrayList<Integer> polygon : model.polygons) {
            sb.append("f");
            for (int zeroBasedIndex : polygon) {
                sb.append(" ").append(zeroBasedIndex + 1);
            }
            sb.append("\n");
        }

        Files.writeString(Path.of(filename), sb.toString());
    }
}